spring:
  application:
    name: spring-gift
  config:
    import: classpath:/application-secret.yml
  h2:
    console:
      enabled: true # H2 console 활성화 여부
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # H2 데이터베이스 URL (MySQL 모드 설정 추가)
    driver-class-name: org.h2.Driver # H2 데이터베이스 드라이버
    username: sa
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 업데이트
    show-sql: true # 실행되는 SQL 쿼리 로깅
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
    open-in-view: false # Open-in-view 설정 비활성화
  sql:
    init:
      mode: always # SQL 초기화 모드

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
